# Generated by Django 5.1.3 on 2024-11-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title post')),
                ('description', models.TextField(verbose_name='Description post')),
                ('author', models.CharField(max_length=100, verbose_name='Name author')),
                ('date', models.DateField(verbose_name='Data post')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
